kind: Deployment
apiVersion: apps/v1
metadata:
   name: hystrix-dashboard
spec:
   replicas: 1
   selector:
      matchLabels:
         app: hystrix-dashboard
   template:
      metadata:
         name: hystrix-dashboard
         labels:
            app: hystrix-dashboard
      spec:
         containers:
         -  name: hystrix-dashboard
            image: qualitto007/hystrix-dashboard:latest
            imagePullPolicy: Always
            ports:
            -  containerPort: 8888
---
kind: Service
apiVersion: v1
metadata:
   name: hystrix-dashboard-k8srv
   labels:
      app: hystrix-dashboard-k8srv
spec:
   type: NodePort
   ports:
   -  nodePort: 30002
      port: 8888
      targetPort: 8888
   selector:
      app: hystrix-dashboard